### PR TITLE
Fix arduino resetting

### LINKED ISSUE #49: Fix velocity
Since the arduino keeps resetting the timestamp, we can't use that timestamp for reliable velocity calculations. One fix would be to use unix timestamps from the Pi side, which I did implement in 1d6d8efc8a57fdfbd473d485dc9286a7d1703cdf, however the velocity still jumped all over the place sometimes, but other times it was fairly stable. 

Another way to fix it would be to still use the arduino timestamp, but whenever it resets, we increment that new value to our old value and keep using that instead. Still not perfect, since it doesn't include the time the arduino took to restart.

Obviously if we can fix the arduino timestamp bug directly, we won't need to do any of this.

### PR DESCRIPTION
**Pull request by harshil21**
Turns out the arduino crashing when moving the board might actually somehow be the code we are using, and not the physical connection. The test_bno08x script I used does not crash the arduino, and that is at 800kHz and no delay in the loop. 

I added sensors one by one and tested - the bno085, then DPS, then the sparkfun GPS. There was no core dump.

I still need to find out the exact reason why the original code fails, but this a big step forward.

Potentially closes #49

### CODE REVIEW

File: esp32/src/sensors.cpp [hunk 1]
```diff
@@ -70,157 +76,127 @@ void collectIMUData(DataPacket &packet) {
...
-            packet.magnetic_z = sensorValue.un.magneticField.z;
-          }
-          executed_cases |= STATUS_BNO08X_MAG;
-          break;
-      }
-    } else {
-      attemptReset = true;
-    }
+  if (bno08x.wasReset()) {
+    Serial.print("BNO08x was reset ");
```
Comment (harshil21) [inline esp32/src/sensors.cpp:80]:
```suggestion
    DEBUG_SERIAL.print("BNO08x was reset ");
```
important to not bug out when reading serial from python

File: payload/data_handling/packets/imu_data_packet.py [hunk 2]
```diff
@@ -8,8 +8,9 @@ class IMUDataPacket(msgspec.Struct):
     This class represents all the data we receive from the IMU.
     """
 
-    arduino_timestamp: int  # In milliseconds
-    voltage: float | None = None
+    timestamp: int  # In milliseconds
+    voltage_pi: float | None = None
```
Comment (harshil21) [inline payload/data_handling/packets/imu_data_packet.py:12]: must document that this is in %

File: payload/data_handling/packets/transmitter_data_packet.py [hunk 3]
```diff
@@ -13,27 +13,28 @@ class TransmitterDataPacket(msgspec.Struct):
...
         return (
-            f"t={self.temperature:.1f},"
-            f"a={self.apogee:.1f},"
-            f"b={self.battery_level:.1f},"
-            f"o=(r={self.orientation[0]:.1f},p={self.orientation[1]:.1f},y={self.orientation[2]:.1f}),"
-            f"tl={self.time_of_landing},"
-            f"mv={self.max_velocity:.1f},"
-            f"lv={self.landing_velocity:.1f},"
-            f"cs={self.crew_survivability * 100:3.0f}"
+            f"temperature={self.temperature*(9/5)+32:.2f}\xc2\xb0F,"
```
Comment (harshil21) [inline payload/data_handling/packets/transmitter_data_packet.py:32]: must document that that sequence is the degree symbol

File: payload/hardware/imu.py [hunk 4]
```diff
@@ -27,8 +29,7 @@ def __init__(self, port: str, baud_rate: int) -> None:
         self._serial = None
         self._buffer = b""  # Initialize an empty buffer to store serial data
 
-    @staticmethod
-    def _process_packet_data(binary_packet) -> IMUDataPacket:
+    def _process_packet_data(self, binary_packet: bytes) -> IMUDataPacket:
```
Comment (harshil21) [inline payload/hardware/imu.py:32]: ig this and the method below can be a staticmethod after all

File: scripts/EncodingTransmittingTest.py [hunk 5]
```diff
@@ -31,14 +31,14 @@ def update_beacon_comment(config_path, new_comment):
 
     found = False
     for i, line in enumerate(lines):
-        if line.startswith("PBEACON"):
+        if line.startswith("PBEACONa"):
```
Comment (harshil21) [inline scripts/EncodingTransmittingTest.py:34]: ?
